const router = require('express').Router();
const auth = require('../middleware/authMiddleware');
const wallet = require('../controllers/walletController');
const checkin = require('../controllers/dailyCheckInController');
router.get('/', auth, wallet.getWallet);
router.get('/coin-packages', auth, wallet.getCoinPackages);
router.get('/activity', auth, wallet.getActivity);
router.get('/gifts/received', auth, wallet.getReceivedGifts);
router.get('/gifts', auth, wallet.getGiftCatalog);
router.get('/monetization', auth, wallet.getMonetizationConfig);
router.get('/withdrawals', auth, wallet.getWithdrawalRequests);
router.post('/withdrawals', auth, wallet.createWithdrawalRequest);
router.get('/check-in', auth, checkin.getStatus);
router.post('/check-in/claim', auth, checkin.claim);
router.put('/coins', auth, wallet.addCoins);
module.exports = router;
